name: LazyLLM ci
on:
  workflow_dispatch:
  push:
    branches:
      - sxy/workflow
    paths-ignore:
      - "**.md"
      - ".git*"
      - "docs/assets/**"
      - "docs/**"

jobs:
  check-rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Show run attempt
        run: echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
      - name: Conditional step if rerun
        if: ${{ github.run_attempt != 1 }}
        run: |
          echo "This is a re-run! (GITHUB_RUN_ATTEMPT=${GITHUB_RUN_ATTEMPT})"
          echo "MY_VAR=seconds" >> $GITHUB_ENV
      - name: Conditional step if first run
        if: ${{ github.run_attempt == 1 }}
        run: |
          echo "This is the first run."
          echo "MY_VAR=first" >> $GITHUB_ENV
      - name: Show ENV
        run: |
          echo $MY_VAR