name: LazyLLM ci
on:
  workflow_dispatch:
  push:
    branches:
      - sxy/workflow
    paths-ignore:
      - "**.md"
      - ".git*"
      - "docs/assets/**"
      - "docs/**"

jobs:
  check-rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Show run attempt
        run: echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
      - name: Conditional step if rerun
        if: ${{ env.GITHUB_RUN_ATTEMPT != '1' }}
        run: echo "This is a re-run! (GITHUB_RUN_ATTEMPT=${GITHUB_RUN_ATTEMPT})"
      - name: Conditional step if first run
        if: ${{ env.GITHUB_RUN_ATTEMPT == '1' }}
        run: echo "This is the first run."