name: LazyLLM ci
on:
  workflow_dispatch:
  push:
    branches:
      - sxy/workflow
    paths-ignore:
      - "**.md"
      - ".git*"
      - "docs/assets/**"
      - "docs/**"

jobs:
  check-rerun:
    runs-on: ubuntu-latest
    steps:
      - name: Show run attempt
        run: echo "GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT"
      - name: Conditional step if rerun
        if: ${{ github.run_attempt != 1 }}
        run: |
          echo "This is a re-run! (GITHUB_RUN_ATTEMPT=${GITHUB_RUN_ATTEMPT})"
          echo "MY_VAR=seconds" >> $GITHUB_ENV
      - name: Conditional step if first run
        if: ${{ github.run_attempt == 1 }}
        run: |
          echo "This is the first run."
          echo "MY_VAR=first" >> $GITHUB_ENV
      - name: Show ENV
        run: |
          echo $MY_VAR
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: cache_result/
          key: python-result-cache-main
      - name: Prepare workspace
        run: |
          mkdir -p workspace_result
          if [ -d cache_result ]; then
            cp -r cache_result/* workspace_result/
          fi
          echo "MY_PATH=$(realpath workspace_result)" >> $GITHUB_ENV
          ls workspace_result -alh
      - name: Exe func
        id: exe_func
        run: |
          echo $MY_PATH
          python -c "print('ok!')" >workspace_result/info2.log 2>&1
      - name: Success branch
        if: ${{ success() && steps.exe_func.conclusion == 'success' }}
        run: |
          echo "✅ Function executed successfully!"
          ls workspace_result -alh
      - name: Success upload cache
        if: ${{ success() && steps.exe_func.conclusion == 'success' }}
        uses: actions/cache/save@v4
        with:
          path: workspace_result/
          key: python-result-cache-main
      - name: Failure branch
        if: ${{ failure() && steps.exe_func.conclusion == 'failure' }}
        run: |
          echo "❌ Function execution failed!"